#更新fork
name: update fork

on: 
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 16 * * *' #0点定时任务

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner != 'Luoyacheng' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set env
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
    - name: Update fork
      run: |
        git checkout -b Luoyacheng-main main
        git pull https://github.com/Luoyacheng/legado.git main
        git checkout main
        git merge --no-ff Luoyacheng-main
        git push origin main